<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows;net9.0-windows;net10.0-windows;net472;net48</TargetFrameworks>
		<IsPackable>false</IsPackable>
		<PlatformTarget>x86</PlatformTarget>
		<DefineConstants>$(DefineConstants);TEST_X86</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="NUnit" Version="3.12.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Lithnet.CredentialProvider\Lithnet.CredentialProvider.csproj" />
		<Compile Include="..\Lithnet.CredentialProvider.UnitTests.x64\BitmapControlTests.cs" Link="BitmapControlTests.cs" />
		<Compile Include="..\Lithnet.CredentialProvider.UnitTests.x64\ComInterop\**\*.cs" Link="ComInterop\%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Samples\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
