<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RegisterForComInterop>false</RegisterForComInterop>
		<Platform>x64</Platform>
		<EnableComHosting>true</EnableComHosting>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Resources\TileIcon.png" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\Lithnet.CredentialProvider.Sample.Framework.x64\InternalLogger.cs" Link="InternalLogger.cs" />
		<Compile Include="..\Lithnet.CredentialProvider.Sample.Framework.x64\ControlKeys.cs" Link="ControlKeys.cs" />
		<Compile Include="..\Lithnet.CredentialProvider.Sample.Framework.x64\TestCredentialProviderTile.cs" Link="TestCredentialProviderTile.cs" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\TileIcon.png" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Lithnet.CredentialProvider\Lithnet.CredentialProvider.csproj" />

		<PackageReference Include="NLog" Version="5.1.1" />
		<PackageReference Include="NLog.Extensions.Logging" Version="5.2.1" />
	</ItemGroup>
</Project>
